### ISSUE TITLE
Special characters in test filenames causing issues with CI server

### ISSUE THREAD

**Issue by losttime** [jfhbrook/node-ecstatic#128]
Jenkins has a problem clearing out the workspace if there are files with special characters. This tests triggers that problem: 檔案.html

**Comment by losttime** [comment]
What do you think? @jesusabdullah

**Comment by jfhbrook** [comment]
Ah Jenkins, why do you have to be the only piece of shit that isn't a TOTAL piece of shit?

**Comment by jfhbrook** [comment]
Can you make your jenkins build shell out to rm -rf that file instead?

**Comment by jfhbrook** [comment]
Also: Is there a corresponding issue for jenkins?

**Comment by jfhbrook** [comment]
I ended up merging https://github.com/jfhbrook/node-ecstatic/pull/129 which "fixes" this by removing tests from the npm package. Extensive, self-indulging commentary here: https://github.com/jfhbrook/node-ecstatic/commit/ebac68d28ddd650daa374a83e1f0ed13722283aa
