### ISSUE TITLE
404 on existing files in multiple instances of ecstatic

### ISSUE THREAD

**Issue by yfr** [jfhbrook/node-ecstatic#136]
I have a setup where i feed `union` with two instances of ecstatic. I want to be able to serve two different directories as one. 

Like so: 
```js

paths = [app, tmp];

paths.forEach(function (path) {
    before.push(ecstatic({
      root: path,
      cache: cache,
      showDir: showDir,
      autoIndex: autoIndex,
      defaultExt: ext,
      handleError: false
    }));
  })
```

The problem is that the first search for a file might give an `ENOENT` and the `res.statusCode` is set to a 404. The second search gives a positive result and the the response is created for serving the file. Sadly the `statusCode` is still the 404 because it's not updated. And so the `union` server response is a 404 with the correct file. 

A quick fix would be to actively set a 200 statusCode if a file is found. This could be here : https://github.com/jfhbrook/node-ecstatic/blob/master/lib/ecstatic.js#L142 or here https://github.com/jfhbrook/node-ecstatic/blob/master/lib/ecstatic.js#L162

What do you think?

I could prepare a PR (with a little help on testing).

**Comment by jfhbrook** [comment]
Interesting use case. I'm pretty sure I actually did set the file to a 200 when found in the past, but that this broke 404 pages. If you can find a way to work around this, then I'd be happy to accept a pull request.

**Comment by yfr** [comment]
I just fiddled around a little. Ran some tests with `request` and tests without test suit checking everything by hand. Looked all good. 

Could this have something to do with the `tap` tests? I don't know this `tap` thing and how it works.

**Comment by jfhbrook** [comment]
The tests aren't broken, if that's what you're asking.

**Comment by yfr** [comment]
No not broken. But something weird going on inside `tap`? I basically just removed `tap` from the test scripts and they work.

**Comment by yfr** [comment]
I dunno. Just poking something :)

**Comment by jfhbrook** [comment]
No, nothing weird. There's a specific case where if a 404.html is being served due to a 404 status, that the status must be a 404 even if 404.html is found. The tests should test for this.

**Comment by yfr** [comment]
I found that the response status code should be set in the serve method. I opened a PR (#139) to address this and my issue with using two instances of ecstatic. Have a look and tell me what you think.

**Comment by yfr** [comment]
Thanks!
Am 06.04.2015 01:19 schrieb "Joshua Holbrook" <notifications@github.com>:
