### ISSUE TITLE
Etag messy code

### ISSUE THREAD

**Issue by Wolfsilver** [jfhbrook/node-ecstatic#163]
in China, timestamp likes this: "`Thu Oct 15 2015 11:17:30 GMT+0800 (中国标准时间)`"

it causes the browser receives messy code.

`etag:"844424930181411-27-Thu Oct 15 2015 11:06:46 GMT+0800 **(-%FD%C6%F6%F4)**"`

**Comment by jfhbrook** [comment]
So that looks gnar.

Does it break anything? What should I do?

**Comment by jfhbrook** [comment]
The relevant line is here https://github.com/jfhbrook/node-ecstatic/blob/master/lib/ecstatic/etag.js#L2

Maybe it's some oddity involving stat.mtime as implemented in your version of node possibly combined with JSON.stringify ? Involving encodings?

**Comment by Wolfsilver** [comment]
It just affects browser cache.

**Comment by Wolfsilver** [comment]
I don't know what kind of encoding the browser use.

I remove the words between '(' and ')'
`('' + stat.mtime).replace(/\s+\(.*\)/, '')`

**Comment by jfhbrook** [comment]
Can you do me a favor and show me the output of:

```js
var fs = require('fs');

var stat = fs.statSync('./package.json'); // or some other file

console.log(stat.mtime);
console.log('' + stat.mtime);
console.log(JSON.stringify(stat.mtime));
```
?

I suspect this is a case of dates stringifying weird, and I'm wondering if JSON.stringify will make it better.

**Comment by jfhbrook** [comment]
I'm also almost certain that the logic for that is totally screwed up and should be applying JSON.stringify to the individual elements then joining, and I just never noticed.

**Comment by jfhbrook** [comment]
Better yet, give this a shot. https://github.com/jfhbrook/node-ecstatic/pull/164

**Comment by Wolfsilver** [comment]
```
Thu May 07 2015 18:26:43 GMT+0800 (中国标准时间)
Thu May 07 2015 18:26:43 GMT+0800 (中国标准时间)
"2015-05-07T10:26:43.089Z"
```

rep [#](#issuecomment-148551103)

**Comment by Wolfsilver** [comment]
```
var fs = require('fs');

var stat = fs.statSync('./package.json'); // or some other file

console.log(stat.mtime);
console.log('' + stat.mtime);
console.log(JSON.stringify(stat.mtime));
console.log(JSON.stringify('' + stat.mtime));
```

output : 

```
Thu May 07 2015 18:26:43 GMT+0800 (中国标准时间)
Thu May 07 2015 18:26:43 GMT+0800 (中国标准时间)
"2015-05-07T10:26:43.089Z"
"Thu May 07 2015 18:26:43 GMT+0800 (中国标准时间)"
```

**Comment by Wolfsilver** [comment]
```
new Date().toJSON();  //"2015-10-19T10:06:20.739Z"
new Date().toISOString(); //"2015-10-19T10:06:22.064Z"
```

**Comment by dotnetCarpenter** [comment]
So
```js
var etag = JSON.stringify([stat.ino, stat.size, stat.mtime.toISOString()].join('-'));
```
?

**Comment by jfhbrook** [comment]
check out #164 

I'm probably gonna merge and close it this weekend

**Comment by Wolfsilver** [comment]
yes

rep [#](#issuecomment-150029176)
