### ISSUE TITLE
The <dir> folder in test/public is breaking git in Windows

### ISSUE THREAD

**Issue by dotnetCarpenter** [jfhbrook/node-ecstatic#172]
One can not have a folder named <dir> in Windows, which prohibit me from cloning and updating my local copy of `node-ecstatic`. Can we called it something else, please?

On Windows the following characters are forbidden in a folder name; `\ / < > | * ? " :`

I currently can not checkout pull requests.

**Comment by dotnetCarpenter** [comment]
I found a way, using [sparse checkout](https://git-scm.com/docs/git-read-tree#_sparse_checkout). After reading through [the commit](https://github.com/jfhbrook/node-ecstatic/commit/4ba99b741b9d703e8a76fb6629668614826ac135#diff-a3ff45033207dccb555f15d57e2e8609) from @jre-g, I see that we can not rename the folder as the attack is only made possible when folders are named in a certain way, that is illegal on Windows.

I will make a PR to the README with the Windows work-around, to enable Windows users to clone and contribute to `node-ecstatic`.

**Comment by jfhbrook** [comment]
Thanks!

**Comment by dotnetCarpenter** [comment]
@jfhbrook well perhaps we could just create the `<div>` directory in the two unit tests and in them test if we're on Windows. If we are then skip the tests.

E.g. `t.notMatch(body, /<dir>/, 'We didn\'t find the unencoded pathname', { skip: true});`

I don't have time at the moment to do it, but if you do, I'll gladly test it.
