### ISSUE TITLE
fallthrough on missing path 403 instead of 404?

### ISSUE THREAD

**Issue by sandro-pasquali** [jfhbrook/node-ecstatic#191]
In my case I want a call to `/some/path` to fall through to an express handler (no autoindex, no dir display, etc).

so:
```
{
  handleError: false,
  showDir: false
}
```
This works as expected, with `/some/path` returning what my route handler says to return.

However, the status header for that *successful* fetching of content is a `403 Forbidden`. This makes no diff to the user, but is an irritant in my case for reasons that aren't important here. Is there some way to get the same behavior without the error status, or a way to change the status returned?

Thanks

**Comment by jfhbrook** [comment]
Okay, this is a little involved.

First: ecstatic does set the statusCode to something it thinks is appropriate when fallthrough happens. The short answer is that this is ecstatic's way of signalling to the next middleware what happened but that I'm generally open to changing it. Some relevant issues:

https://github.com/jfhbrook/node-ecstatic/issues/183
https://github.com/jfhbrook/node-ecstatic/issues/154

Now, given that, you would *expect* a 404, not a 403. 2 suggestions:

1. What path are you trying to access? I found [this gem](https://github.com/jfhbrook/node-ecstatic/commit/272c7f958104ee5afa0cd491ba8adcabb2a5c011), maybe it's related?
2. Have you turned off autoIndex? [The other way to get a 403 requires that autoindex is on.](https://github.com/jfhbrook/node-ecstatic/blob/master/lib/ecstatic.js#L153-L166)

**Comment by sandro-pasquali** [comment]
Thanks... I think what I need is covered by #154 -- what I really need is for ecstatic to not set a response header when yielding control to what is ultimately my own route handler. I also understand that this is a tricky thing for various reasons. I'll close this as it is essentially a duplicate.

**Comment by jfhbrook** [comment]
I bring up #183 because it's the closest proposal to an alternate API.
