### ISSUE TITLE
ecstatic.js unexpected character '#'

### ISSUE THREAD

**Issue by Kozhemyak** [jfhbrook/node-ecstatic#194]
Hi all! I link this module in server file js, and when i am trying to make a bundle file using webpack and babel-loader i receive an error like this:

ERROR in ./~/ecstatic/lib/ecstatic.js
    Module parse failed: ...\node_modules\ecstatic\lib\ecstatic.js Unexpected character '#' (1:0)
    You may need an appropriate loader to handle this file type.
    | #! /usr/bin/env node
    | var path = require('path'),
     @ ./src/server/server.js 5:15-34
     @ multi (webpack)-dev-server/client?http://0.0.0.0:80 webpack/hot/dev-server ./src/server/server.js

Maybe it doen't depend on module.

**Comment by jfhbrook** [comment]
That's a hashbang, which allows for being able to execute ./lib/ecstatic.js on the command line. That's not a bug. If you want to be able to webpack things with hashbangs in them, talk to *them*.

All that said, I'd be shocked if it made any kind of sense to webpack ecstatic, considering that it's a server-side static fileserving component.
