### ISSUE TITLE
.nyc_output directory

### ISSUE THREAD

**Issue by joshas** [jfhbrook/node-ecstatic#206]
What's inside .nyc_output directory? I found it in node_modules/ecstatic/ after installing ecstatic as dependency. Should it be included in npm package at all?

**Comment by jfhbrook** [comment]
It's an artifact of testing code coverage. It's not particularly harmful, but could be added to the .npmignore to decrease total package size.

I have some spare cycles, so I'll add some things to the .npmignore that'll kick in next time I publish.

**Comment by jfhbrook** [comment]
https://github.com/jfhbrook/node-ecstatic/commit/df39a58b830931cd6cab52876719b40400b6c702

Cheers
