### ISSUE TITLE
Update mime to a version without a security vulnarability

### ISSUE THREAD

**Issue by dotnetCarpenter** [jfhbrook/node-ecstatic#212]
I stumble on this: https://david-dm.org/jfhbrook/node-ecstatic while looking at https://github.com/jfhbrook/node-ecstatic/blob/master/CONTRIBUTING.md#a-few-other-minor-guidelines

That seems pretty bad since it's not a dev dep and we have many hooks to set custom mime types, which someone might set from an entrusted source.

**Comment by jfhbrook** [comment]
oh wow.

questions:

* what version of mime are we on now?
* what are the breaking changes between versions?

**Comment by jfhbrook** [comment]
shit, this means we have to solve https://github.com/jfhbrook/node-ecstatic/issues/66 yeah?

**Comment by jfhbrook** [comment]
I guess we can do the upgrade, major semver ourselves, and kick the can on how we can make mime truly pluggable since I don't think anyone has actually tackled that problem yet

**Comment by dotnetCarpenter** [comment]
Yes there is breaking change. If I update and run `node_modules/.bin/tap test/mime.js` I get a lot of errors.

1. not ok `mime.lookup` is not a function
2. custom definition of mime-type with the mime package
  not ok Attempt to change mapping for "opml" extension from "text/x-opml" to "application/xml". Pass `force=true` to allow this, otherwise remove "opml" from the list of extensions for "application/xml".
3. not ok `mime.load` is not a function

**Comment by dotnetCarpenter** [comment]
@jfhbrook heh I thought I fixed #66 in #143 one and a half year ago ;)
I'm sorry but I really don't have time at the moment. I use ecstatic every day but am behind on project that needs to be wrapped up ASAP. I just needed the log, so I did it. But I hope to have time next year to give ecstatic some :heart:

**Comment by dotnetCarpenter** [comment]
There was an idea about using **mime-magic**. Is that module out?

**Comment by jfhbrook** [comment]
yeah I was thinking about that! I don't remember why I didn't like the idea at the time. Maybe I was worried about cross-platform support? That seems squared with them shipping the windows binary. We already have to do a major change, so that's not an issue either

**Comment by dotnetCarpenter** [comment]
Do we need a coding date in January to refactor mime types, middleware and make ecstatic SPA friendly?

**Comment by jfhbrook** [comment]
ahaha oh man, yeah maybe

**Comment by dotnetCarpenter** [comment]
hehe... I'll be up for a weekend hackathon or something like that if *life* doesn't get in the way.

**Comment by jfhbrook** [comment]
yeah, gotcha.

I did some digging, looks like this mighta gotten patched in v1? https://github.com/broofa/node-mime/releases

**Comment by jfhbrook** [comment]
hell yeah he backported the fix

I'll have a release for this out today!

**Comment by jfhbrook** [comment]
https://github.com/jfhbrook/node-ecstatic/commit/2eb212d87c14e36f76986f487711b03c0ea2267c and published in 3.1.1.

Thanks for lookin' out!
