### ISSUE TITLE
Add way to hide file permissions

### ISSUE THREAD

**Issue by benevbright** [jfhbrook/node-ecstatic#214]
Thanks for a wonderful module.

I want to hide files' permission.
Is there any solution for this?
  
I can't find it from the provided options.

**Comment by jfhbrook** [comment]
It's not a currently exposed option, but I would definitely take this as a pull request!

**Comment by benevbright** [comment]
Thanks for your kind response :)

**Comment by mmmm1998** [comment]
I think, the issue maybe closed, isn't it?

**Comment by jfhbrook** [comment]
yes, just forgot.

**Comment by benevbright** [comment]
Thank @mmmm1998 . I came by now because I thought I have time to deal with. 
But it's already done! I appreciate it.

**Comment by benevbright** [comment]
I made an advanced version of @mmmm1998 's PR.
I appreciate to @mmmm1998 .

https://github.com/jfhbrook/node-ecstatic/pull/219
