### ISSUE TITLE
Http Content-type header field missing on *.mjs files

### ISSUE THREAD

**Issue by adiba** [jfhbrook/node-ecstatic#217]
Should be the same as in *.js files (eg `application/javascript; charset=UTF-8`).
The `content-length` field is missing as well.

**Comment by jfhbrook** [comment]
The former is an issue for mime@1 https://github.com/jfhbrook/node-ecstatic/blob/master/package.json#L29 . Also, you should be able to add your own content-types with the mimeTypes option.

The second would be a pretty egregious but unrelated bug which really really should not be happening--and if it were, it would be a specific edge case most likely not related to mime types. You should investigate this further and send a separate bug report if you can suss this out for sure.

**Comment by adiba** [comment]
The mjs type is already registered: https://github.com/broofa/node-mime/blob/v1.4.0/types.json

**Comment by jfhbrook** [comment]
ok, well, this should definitely work then, same as any other content type. Something much stranger is going on.

**Comment by jfhbrook** [comment]
What command are you running? Do you have a repro case I can try to stand up locally?

**Comment by adiba** [comment]
I am using https://www.npmjs.com/package/http-server

**Comment by jfhbrook** [comment]
OK, I don't support http-server.

If you can get this to reproduce with ecstatic's included cli command, then we can re-open.

**Comment by adiba** [comment]
With the CLI I get `content-type:application/octet-stream` on one file (my .mjs module), but `content-type:application/javascript; charset=UTF-8` on my main.mjs

**Comment by adiba** [comment]
The module loaded via `import ... from './....mjs';` has the wrong content type. `.mjs` files loaded via `script` tag do not.

**Comment by adiba** [comment]
@jfhbrook

**Comment by jfhbrook** [comment]
I need a full repro case. I need actual files with actual path locations and a cli command for spinning up ecstatic.
