### ISSUE TITLE
Wrong behavior of `application/wasm` mime type

### ISSUE THREAD

**Issue by rqrqrqrq** [jfhbrook/node-ecstatic#220]
Current webassebmly spec says
> Note: extra parameters are not allowed, including the empty `application/wasm;`.
https://webassembly.github.io/spec/web-api/index.html#streaming-modules

For now ecstatic adds charset in `Content-Type` for all filetypes, so mimetype for wasm files will be `application/wasm; charset=utf-8`. Can we somehow disable this for files with `application/wasm` mimetype (or for binary files at all?)?

I'll be happy to create PR if you tell me right way to figure out exclusions.

**Comment by dcodeIO** [comment]
Just got hit by this as well. This basically breaks ´WebAssembly.instantiateStreaming` incl. WebAssembly source map support.

**Comment by jfhbrook** [comment]
https://github.com/jfhbrook/node-ecstatic/blob/master/lib/ecstatic.js#L242-L247 potentially a bug in mime@1 ? upgrading mime is part of a bigger project.

**Comment by dcodeIO** [comment]
Yeah, I think that's the cause. Seems that the mime package removed the charset functionality entirely in v2. Ideally, if there'd be a way to detect that a mime type is indicating a binary file, appending the charset could simply be skipped, or something like that.

**Comment by takahirox** [comment]
I'd like to request "charset=utf-8" skipping for binary files. `createImageBitmap()` doesn't work for images whose mime type includes "charset=utf-8".

https://bugzilla.mozilla.org/show_bug.cgi?id=1413806

**Comment by bytex64** [comment]
Seems like ecstatic isn't using `mime.charsets.lookup()` correctly. Here's the entire source for the function from the `mime` module:

```
lookup: function(mimeType, fallback) {
  // Assume text types are utf8
  return (/^text\/|^application\/(javascript|json)/).test(mimeType) ? 'UTF-8' : fallback;
}
```

And here's how ecstatic is using it:

```
charSet = mime.charsets.lookup(contentType, 'utf-8');
if (charSet) {
  contentType += `; charset=${charSet}`;
}
```

`mime.charsets.lookup()` returns either the detected charset ('UTF-8') or the given fallback (in ecstatic's case, 'utf-8'), but ecstatic is treating it like it returns a bool. Since a non-empty string is always true, the charset 'utf-8' is always added. The fix is to remove the fallback ('utf-8') parameter (making the fallback case a falsy `undefined`) and/or check specifically for `charset == 'UTF-8'`.

I was wondering if maybe that changed lately, but it seems `mime.charsets.lookup()` has worked that way as far back as I looked into the history (~2011).

**Comment by jfhbrook** [comment]
The mime upgrade has been a long time coming. If you're willing to put the work into it I'd love to merge that and just bang out a major release.

**Comment by BigBlueHat** [comment]
It looks like the biggest thing missing (according to #218 and some follow-up research) is the loss of the `.load()` system. They do support passing in custom media type lists in JSON, but we'd need to provide some parsing/handling of the `.types` format (as seen in Apache's [mime.types](https://svn.apache.org/repos/asf/httpd/httpd/branches/1.3.x/conf/mime.types)).

For now I'll reach out to see if the `mime` library plans to add this (even as a separate module/script) or if we would need to directly.

**Comment by jfhbrook** [comment]
If you like! Though I don't think they were interested in supporting apache mime files anymore.

One suggestion from that ticket was to make it so you could implement your own lookup function, which I think is actually pretty good and a solid way to punt on this. But I'll take it either way.

**Comment by BigBlueHat** [comment]
The `new Mime()` constructor can take the JSON files created by `mime-db`, so it's really about (afaict) getting `.types` into the `.json` format `mime` (and `mime-db`) use.

Just filed such an issue here, fwiw: https://github.com/jshttp/mime-db/issues/133

**Comment by jfhbrook** [comment]
I think #240 fixes this.
