### ISSUE TITLE
consider using relative url for href to work behind a proxy

### ISSUE THREAD

**Issue by panlina** [jfhbrook/node-ecstatic#233]
Hi,
I'm using ecstatic behind a proxy, something like proxying http://localhost/a to http://localhost:8080, where 8080 is the port ecstatic is listening to. The problem is that ecstatic uses absolute url for `href`, which resolves to a url where the file path is directly appended to the host part, instead of the current url.
For instance, when browsing from http://localhost/a, clicking folder `f` navigates to http://localhost/f/, instead of http://localhost/a/f/.
I noticed that there's a `baseDir` option, but it's irrelevant here since the base url(`/a`) is already eaten by the proxy before `baseDir` applies. 
Using relative url for `href` may be a solution, but I'm not sure whether you are using absolute path for some reason. How do you think?

**Comment by wll8** [comment]
@panlina Hello, how do you deal with this problem?

**Comment by panlina** [comment]
It can not be solved unless you modify the code. You may ask the author to take this into account.

**Comment by jfhbrook** [comment]
Feel free to make a pull request!

**Comment by wll8** [comment]
[show-dir/index.js#L98](https://github.com/jfhbrook/node-ecstatic/blob/master/lib/ecstatic/show-dir/index.js#L98):
You can switch these two lines of code by option.

``` js
// let href = `${parsed.pathname.replace(/\/$/, '')}/${encodeURIComponent(file[0])}`;
let href = `${encodeURIComponent(file[0])}`;
```

The problem between absolute path and relative path can be solved.

**Comment by jfhbrook** [comment]
Oh! If that's all that's needed I'll gladly change that behavior, I just need the time to manually QA it

**Comment by panlina** [comment]
Yes, that's all that is needed, but I think an option is not needed, just change it to be relative path.

**Comment by wll8** [comment]
Options are used to ensure that they do not conflict with the author's previous ideas.

**Comment by panlina** [comment]
Understood. That's what I'm asking at the end of my post.
