### ISSUE TITLE
Unable to run CLI due to invalid line endings on Linux

### ISSUE THREAD

**Issue by tehlordvortex** [jfhbrook/node-ecstatic#238]
After installing ecstatic with `yarn global add ecstatic`, I'm unable to run the command. It dies with the following error message:
`/usr/bin/env: ‘node\r’: No such file or directory`
This seems to be an issue with the code using CRLF line-endings instead of just LF on Linux.

OS: Ubuntu 18.04 LTS 64bit
Node version: 10.10.0
Yarn version: 1.12.1

**Comment by thornjad** [comment]
@tehlordvortex could you try reinstalling the package? Examining the files with `hexdump` shows Unix-only, no `\r`'s, so I'm thinking it may be on your end (maybe something with Yarn?).

**Comment by kla** [comment]
I'm seeing the same thing. Seems to only happen when using the symlink in `.bin`:

```
$ node_modules/.bin/ecstatic 
env: node\r: No such file or directory

$ node node_modules/ecstatic/lib/ecstatic.js
ecstatic serving /tmp/test at http://0.0.0.0:8000
```

If I run `dos2unix` on `ecstatic.js` that will fix it:

```
$ dos2unix node_modules/ecstatic/lib/ecstatic.js 
dos2unix: converting file node_modules/ecstatic/lib/ecstatic.js to Unix format...

$ node_modules/.bin/ecstatic 
ecstatic serving /tmp/test at http://0.0.0.0:8000
```

**Comment by jfhbrook** [comment]
possible that the deploy package has windows line endings on accident? I think the last release or two were via windows...

**Comment by jfhbrook** [comment]
ok try 3.3.1 and lmk

**Comment by kla** [comment]
Works!

```
$ node_modules/.bin/ecstatic 
ecstatic serving /tmp/test at http://0.0.0.0:8000
```

**Comment by jfhbrook** [comment]
Great! Unfortunate that npm publish on windows is busted 🙄 but glad to fix!
