### ISSUE TITLE
What version of Node are we targeting? (OutgoingMessage & emit close)

### ISSUE THREAD

**Issue by ronag** [jfhbrook/node-ecstatic#248]
If I remember correctly, OutgoingMessage does not always `emit` close in all versions of Node.  Something we depend on. 

Should we use `eos` or `on-finished` to make sure we are as compatible as possible?

**Comment by jfhbrook** [comment]
Totally ok using on-finished.

As far as versions of node targeted: I think the test matrix currently goes from v6 to v10 but I'm mostly just trying to keep ~ last two LTS's. I figure a few years back is fine. Certainly not supporting v0.10 anymore!
