### ISSUE TITLE
npm high severity vulnerability

### ISSUE THREAD

**Issue by kirkins** [jfhbrook/node-ecstatic#254]
Hello, I have a project with the `http-static` package. When I do `npm install` it tells me there is a vulnerability in my dependencies. Running audit show this project.

Looking at the npm site it seems this is only the possibility of a DDOS attack?

I'm only using this for a class and not production but I feel like the vulnerability message means I'll have to find another package even though `http-static` is working just fine.

Are there any plans to stop this error from showing up?

![Screenshot from 2019-04-30 11-19-40](https://user-images.githubusercontent.com/9503662/56973079-25534480-6b3a-11e9-8f95-ab8a0a230d8f.png)

**Comment by jfhbrook** [comment]
the way to make this message go away is to convince the http-server people to upgrade to 4.1.2.

**Comment by kirkins** [comment]
Ah I see, I tried changing it to use 4.1.2 and it breaks. Guess I'll need to find a new package.

**Comment by jfhbrook** [comment]
"it breaks" is super vague

**Comment by kirkins** [comment]
Running `npm test` after upgrading to 4.1.2 causes 4 of their 25 tests to fail.

```
  When http-server is listening on 8080 When http-server is proxying from 8081 to 8080 it should serve files from the proxy server root directory and file content
    ✗ should match content of the served file 
        »        
        actual expected 
         
        hello, I know nodejitsu 
         // macros.js:14
  When http-server is listening on 8083 with username "good_username" and password "good_password" and the user requests an existent file with correct auth details and file content
    ✗ should match content of served file 
        »        
        actual expected 
         
        hello, I know nodejitsu 
         // macros.js:14
  When http-server is listening on 8080 it should serve files from root directory and file content
    ✗ should match content of served file 
        »        
        actual expected 
         
        hello, I know nodejitsu 
         // macros.js:14
  When gzip and brotli compression is enabled and a compressed file is available and a request accepting only gzip is made
    ✓ response should be gzip compressed
  When http-server is listening on 8080 When http-server is proxying from 8081 to 8080 it should fallback to the proxied server
    ✓ status code should be the endpoint code 200
  When http-server is listening on 8080 When http-server is proxying from 8081 to 8080 it should fallback to the proxied server and file content
    ✗ should match content of the proxied served file 
        »        
        actual expected 
         
        hello, I know nodejitsu 
         // macros.js:14

✗ Broken » 21 honored ∙ 4 broken (0.104s) 
```

**Comment by jfhbrook** [comment]
oh. http-server's tests aren't my problem.

**Comment by kirkins** [comment]
I don't care either, switching to https://github.com/lwsjs/local-web-server takes 5 minutes.

**Comment by thornjad** [comment]
We're working on those tests @kirkins, this is a major version upgrade for us, there's more to it than just upgrading the ecstatic dependency. indexzero/http-server#520

**Comment by kirkins** [comment]
@thornjad I'll keep an eye out for that, been using http-server for many years now without problem.
