### ISSUE TITLE
Version 1.4.0 gone in npm

### ISSUE THREAD

**Issue by NoExcuseForCode** [jfhbrook/node-ecstatic#257]
One of our module has dependency on 1.4.0 which is not available in npm, Can you reinstate the same.

**Comment by haridsv** [comment]
Duplicate of issue #255

**Comment by jfhbrook** [comment]
https://github.com/jfhbrook/node-ecstatic/issues/255#issuecomment-489101365

Like this comment says, there are versions available in the 2 3 and 4 majors but not for v1.
