### ISSUE TITLE
continue maintaining ecstatic

### ISSUE THREAD

**Issue by Xmader** [jfhbrook/node-ecstatic#262]
According to #259 *"I will not accept patches or push updates to ecstatic going forward. This includes security updates."*, this project is unmaintained and deprecated, but it breaks http-server and packages depending on http-server in version 3.3.2 . (https://github.com/indexzero/http-server/issues/525)

I created a fork, and I will continue maintaining the new extatic.

https://github.com/node-extatic/extatic

```
npm i extatic
```

**Comment by jfhbrook** [comment]
I would deeply appreciate it if you changed the name of your project to something that isn't `ecstatic`.

**Comment by jfhbrook** [comment]
but if you want to maintain a fork rock it! just please, change the name

**Comment by lwxbr** [comment]
the name should be egostatic.

**Comment by tchakabam** [comment]
@lwxbr :)
