### ISSUE TITLE
Failed to compile while building with webpack as dependency

### ISSUE THREAD

**Issue by Dharmendra205111014** [jfhbrook/node-ecstatic#274]
ERROR  Failed to compile with 1 errors                                                                                                                               15:35:06

 error  in ./node_modules/ecstatic/lib/ecstatic.js

Module parse failed: Unexpected character '#' (1:0)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
> #! /usr/bin/env node
| 
| 'use strict';

 @ ./node_modules/http-server/lib/http-server.js 5:15-34
 @ ./src/background.ts
 @ multi ./src/background.ts

Suggestion:
As #! /usr/bin/env node is could used for cli purpose, using it as direct node dependency and bundle it with with webpack, the bundler is unable to understand the file. we should isolate the bin and main part of scripts to be used by different usecases.

PS: I am using it in on of my electron based project and need to bundle to distribute it.

**Comment by jfhbrook** [comment]
I don't maintain this program anymore. Find a different one.
