### ISSUE TITLE
include charset in Content-Type header

### ISSUE THREAD

**Issue by paulwalker** [jfhbrook/node-ecstatic#44]

**Comment by markandrus** [comment]
I know this is an old thread, but it would be very useful to be able to override the charset. mime's charset lookup function is basically "return 'utf-8' if it has 'text' appears in the MIME type", which is incorrect for many applications.

**Comment by jfhbrook** [comment]
It's late my time and idk when I'll get a chance to dig into the details of your request, but this sounds like something I would accept as a PR if you want to take a crack at it.

**Comment by dotnetCarpenter** [comment]
@markandrus Can't you already do that with [opts.mimeTypes](https://github.com/jfhbrook/node-ecstatic#optsmimetypes)?

**Comment by dotnetCarpenter** [comment]
Looks like you can not, due to https://github.com/broofa/node-mime/blob/master/mime.js#L104 and https://github.com/jfhbrook/node-ecstatic/blob/master/lib/ecstatic.js#L201.

or.... what does `ecstatic --mime-types "{ mimeType: { 'what/ever;charset=us-ascii': ['php']  }` do?
