### ISSUE TITLE
Add API entry points for custom and async mime lookup

### ISSUE THREAD

**Issue by mk-pmb** [jfhbrook/node-ecstatic#66]
Hi, I'm trying to serve text files with unusual filename extensions, which wind up as octet-stream due to ecstatic's reliance on the "mime" module:

```
sven:/gr2$ nodejs -e 'console.log(require("mime").lookup("common.flp"));'
application/octet-stream
```

I'd prefer them to be resolved according to my local mime types DB:

```
sven:/gr2$ file --mime common.flp
common.flp: text/plain; charset=us-ascii
```

This could be achieved by using the "mime-magic" module:

```
sven:/gr2$ nodejs -e 'var mime = require("mime-magic"); mime("common.flp", console.log);'
null 'text/plain'
```

It seems that in the "mime" module, there's currently no way to distinguish known octet-streams from fallback octet-streams ([mime bug #55](https://github.com/broofa/node-mime/issues/55)).

<del>I'd be glad if you could implement the mime-magic lookup into mainstream ecstatic.</del>

(Edit 2015-12-08: The filename-based lookup is fine for default. If mime-magic lookup ever gets into mainstream ecstatic, only use it as a fallback for when filename-based mime has no idea.)

**Comment by dotnetCarpenter** [comment]
I would really like this in [http-server](https://github.com/indexzero/http-server), so guess this is the *upstream* repo to follow. It's a (**REALLY**) nice-to-have not a need-to-have, yet.

**Comment by mk-pmb** [comment]
FYI, I had tried tackling this again a few days ago, but couldn't get the tests to pass for current master (3.0.0), even with env proxy config adjusted to no proxy. Maybe the non-proxy parts of #180 can help fix them so anyone interested in this, consider fixing that one, too.

**Comment by mk-pmb** [comment]
I'd like to change our dependency on the old `mime@^1` to the `mundane-mime-v1` proxy package I just published, so we can still use v1 for people who like to `.load()` Apache style MIME type lists, while at the same time allowing partial migration to the latest `mime`. Yes/no?

**Comment by jfhbrook** [comment]
Oh, to better enable replacing the dependency in a scenario where npm dedupes?

**Comment by mk-pmb** [comment]
Actually it was just the easiest way to make both versions live side by side on my machine without npm going on a rampage, enforcing default whitespace style in hundreds of `package.json`s even when no values were changed. However, now considering your question, it might indeed have been a side effect of a dedupe attempt.

**Comment by mk-pmb** [comment]
I'll just go through with that change because my dev server just failed due to the limbo.

**Comment by jfhbrook** [comment]
Looks like this shoulda been closed with https://github.com/jfhbrook/node-ecstatic/pull/143/files
