### ISSUE TITLE
allow different cache times for different urls

### ISSUE THREAD

**Issue by skivvies** [jfhbrook/node-ecstatic#94]
From nodeapps/http-server#63:

> Currently http-server allows you to configure the "cache-control: max-age" value for all urls. But often you want a short max-age for e.g. /{index.html} and a long max-age for urls to versioned assets like /styles/f35ac111.main.css.
>
> Would you accept a patch to allow specifying different max-ages for different urls?

I realized http-server is just using ecstatic under the hood, which also only allows setting a single max-age for all responses.

Any suggestions on the simplest approach to giving versioned assets a longer max-age than non-versioned assets? Would be happy to submit a patch if there is interest in supporting this.

**Comment by TehShrike** [comment]
That pull request never materialized apparently? :-) I could use this, and the function mechanism seems perfect to me.

**Comment by jfhbrook** [comment]
Yeah, to my recollection no PR.

**Comment by grrowl** [comment]
:+1: unfortunately we changed course and didn't need this functionality, kudos to @TehShrike for addressing this

**Comment by TehShrike** [comment]
Oh, I don't care about you guys, *I* need this! ;-) <3
